Update lightdash.yml
testing

diff --git a/.github/workflows/lightdash.yml b/.github/workflows/lightdash.yml
--- a/.github/workflows/lightdash.yml
+++ b/.github/workflows/lightdash.yml
@@ -40,7 +40,10 @@ jobs:
         ssh -o StrictHostKeyChecking=no -fN -L 5433:high-rewards-aurora-postgresql-reader.cjy248yiebxq.us-east-1.rds.amazonaws.com:5432 ubuntu@52.87.194.221
     - name: Verify SSH Tunnel
       run: |
-        curl --connect-timeout 10 localhost:5433 || echo "Failed to connect to SSH tunnel"
+        # Wait for the tunnel to establish
+        sleep 10
+        # Check if the port is listening
+        nc -zv localhost 5433 || echo "Failed to connect to SSH tunnel"
     - name: Set up dbt profile
       run: |
         mkdir -p ~/.dbt
