Update lightdash.yml
adsfgads

diff --git a/.github/workflows/lightdash.yml b/.github/workflows/lightdash.yml
--- a/.github/workflows/lightdash.yml
+++ b/.github/workflows/lightdash.yml
@@ -38,7 +38,9 @@ jobs:
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh -o StrictHostKeyChecking=no -fN -L 5433:high-rewards-aurora-postgresql-reader.cjy248yiebxq.us-east-1.rds.amazonaws.com:5432 ubuntu@52.87.194.221
-
+    - name: Verify SSH Tunnel
+      run: |
+        curl --connect-timeout 10 localhost:5433 || echo "Failed to connect to SSH tunnel"
     - name: Set up dbt profile
       run: |
         mkdir -p ~/.dbt
